### ISSUE TITLE
issue7: headings in home tab

### ISSUE THREAD

**Issue by Satish55** [bravokeyl502/SPAT#10]
in all home tabs, headings are like "Home . Dashboard", dashboard is to be removed

**Comment by bravokeyl502** [comment]
Is TL okay with this ? Let me know.

**Comment by Satish55** [comment]
TL told "I already told badra to make that change, may be badra forgot it".

**Comment by bravokeyl502** [comment]
Done

**Comment by bravokeyl502** [comment]
@Satish55 , Any changes needed here ?

**Comment by Satish55** [comment]
dashboard is not removed......?

**Comment by Satish55** [comment]
okay... but i think "devices . home" is better than "home", then all 4 tabs will be uniform

**Comment by bravokeyl502** [comment]
Check now after syncing..

**Comment by Satish55** [comment]
okay..... perfect (Y)
