### ISSUE TITLE
Hovering of tabs

### ISSUE THREAD

**Issue by Satish55** [bravokeyl502/SPAT#6]
suppose if we click on network (or dashboard), and cursor is put on network (or dashboard). There is no hovering (anywhere) , which may create confusion "what is the tab opened now?"

**Comment by Satish55** [comment]
can we put some comma or hyphen or something beside day. eg: Mon, date, time

**Comment by Satish55** [comment]
can we put some comma or hyphen or something beside day. eg: Mon, date, time

**Comment by Satish55** [comment]
In control tab, AUTO image can be centered

**Comment by bravokeyl502** [comment]
`
.page-sidebar .page-sidebar-menu > li.active>a:hover,
.page-sidebar .page-sidebar-menu > li.active > a:hover > i[class*="icon-"]{
	background: #f2f6f9;
	color: #5b9bd1;
}
`
Code fixed
