### ISSUE TITLE
Have to change position of notifications

### ISSUE THREAD

**Issue by Satish55** [bravokeyl502/SPAT#7]
issue4: As soon as i login in google, notifications pull down menu is by default opening.....

**Comment by bravokeyl502** [comment]
It's working perfect for me..
Please confirm once again.

**Comment by Satish55** [comment]
yeah..... it's perfect. i have overseen it yesterday.

**Comment by Satish55** [comment]
When we login as a first time user or a user who had not saved password, in google, then we notifications tab is by default getting opened.

**Comment by bravokeyl502** [comment]
Now there will no issue as it is not opened on hover , design decision is made to open the dropdown menu on click.

@Satish55  , Please check this issue and close if it is okay.
